config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'

  resources :videos, :only => [:index, :show] do
    member do
      post "user_click"
      post "set_active_status"
      post "set_featured_status"
    end
  	resources :comments, only: [:create, :update]
  	resources :ratings, only: [:create, :update]
  end
  resources :comments, only: [:destroy]

  get "/about", to: "home#about"
  post "/about", to: "home#send_contact"

  get "/admin", to: "admin#index"
  post "/admin/crawl_page", to: "admin#crawl_page"
  post "/admin/update_about", to: "admin#update_about"
  post "/admin/crawl_categories", to: "admin#crawl_categories"
end

app/models/video.rb
class Video < ApplicationRecord
  has_and_belongs_to_many :categories
  has_many :comments, -> { where(parent_id: nil).order("created_at desc") }
  has_many :ratings
  has_many :user_video_views
  
  default_scope { where(active: true) }
  scope :title_like, -> (title) { where("lower(title) like ?", "%#{title.downcase}%") }
  scope :author_like, -> (author) { where("lower(author) like ?", "%#{author.downcase}%") }
  scope :has_topic, -> (topic_id) { joins(:categories).where("categories.id = ?", topic_id) }
  scope :greater_than_date, -> (date) { where("date > ?", date)}

  def related_videos
    if self.categories.any?
  	  return Video.has_topic(self.categories.sample.id).sample(4)
    end
    return Video.all.sample(4)
  end

  def average_rating
    if self.ratings.any?
      return self.ratings.average(:value)
    end
    return nil
  end

  def self.include_inactive
    unscoped
  end

  def date_friendly
    return self.date.strftime("%B %Y")
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:user_click]

  def index
    @video_filter = VideoFilter.new(params)

    @videos = Video.where(nil)
    if @video_filter.any_filters?
      unless @video_filter.author.blank?
        @videos = @videos.author_like(@video_filter.author)
      end
      unless @video_filter.title.blank?
        @videos = @videos.title_like(@video_filter.title)
      end
      unless @video_filter.topic.blank?
      	@videos = @videos.has_topic(@video_filter.topic)
      end
      unless @video_filter.date == 0
        @videos = @videos.greater_than_date(DateTime.now << @video_filter.date)
      end
      unless @video_filter.rating.blank?
        # TODO: move to scope somehow?
        @videos = @videos.select { |vid| vid.ratings.any? and vid.average_rating >= @video_filter.rating.to_d }
      end

      # TODO: these below once we have those stats on the video...
      # TODO: length/duration
      # TODO: date/age
      @videos = @videos.order(date: :desc)
    else
      @videos = Video.all.sample(40)
    end

    
    load_filter_inputs_data
  end

  def show
    # TODO: show video not found if user isn't admin? So people can't save URLs?
    @video = Video.include_inactive.find(params[:id])
    @related_videos = @video.related_videos
    @new_comment = Comment.new

    @rating = Rating.new
    if user_signed_in?
      user_rating = @video.ratings.find_by user_id: current_user.id
      if user_rating
        @rating = user_rating
      end
    end
  end

  def set_active_status
    @video = Video.include_inactive.find(params[:id])
    logger.info "Setting video #{@video.id} active flag to #{params[:featured]}"
    @video.active = params[:active]
    unless @video.active?
      logger.info "Setting video #{@video.id} featured flag to false, since video is being set inactive"
      @video.featured = false
    end
    @video.save

    # TODO: return view or success or something
  end

  def set_featured_status
    @video = Video.find(params[:id])
    unless @video.nil?
      logger.info "Setting video #{@video.id} featured flag to #{params[:featured]}"
      @video.featured = params[:featured]
      @video.save
    else
      # video not found or inactive - unable to set as featured
    end

    # TODO: return view or success or something
  end

  def user_click
    if user_signed_in?
      UserVideoView.create({:user_id => current_user.id, :video_id => params[:id], :emailed => false})
    end
    head :no_content
  end
end

app/views/videos/_admin.html.haml
.col-12
  .card
    .card-body
      %h4.card-title= "ADMIN"
      #viewCount
        = "View count: #{@video.user_video_views.count}"
      #active
        - if @video.active?
          = "Video is active"
          = form_tag("#{@video.id}/set_active_status?active=false", method: :post, remote: true) do
            = submit_tag "Make Inactive", class: "btn btn-primary refreshAfterClick"
        - else
          = "Video is inactive"
          = form_tag("#{@video.id}/set_active_status?active=true", method: :post, remote: true) do
            = submit_tag "Make Active", class: "btn btn-primary refreshAfterClick"
      - if @video.active?
        #featured
          - if @video.featured?
            = "Video is featured"
            = form_tag("#{@video.id}/set_featured_status?featured=false", method: :post, remote: true) do
              = submit_tag "Remove Featured", class: "btn btn-primary refreshAfterClick"
          - else
            = "Video is not featured"
            = form_tag("#{@video.id}/set_featured_status?featured=true", method: :post, remote: true) do
              = submit_tag "Make Featured", class: "btn btn-primary refreshAfterClick"

:javascript
  $(document).ready(function() {
    $(".refreshAfterClick").on("click", function() {
      setTimeout(function() {
        location.reload();
      }, 500);
    });
  });

app/views/videos/_comment.html.haml
.comment
  .head
    %span.name.font-weight-bold= comment.user.public_name
    %span.age= (time_ago_in_words(comment.created_at) + " ago").upcase
  .body= comment.body
  - if user_signed_in? && (current_user.id == comment.user_id || current_user.admin?)
    = link_to "Delete", comment, :method => :delete, :remote => true, :class => "delete-comment"
    - unless comment.is_sub_comment?
      |
  - unless comment.is_sub_comment?
    %a.reply-link{ href: "#"} Reply
    .replies-wrapper
      .replies
        - comment.sub_comments.each do |sc|
          = render partial: "comment", object: sc, as: :comment
      .reply-form
        - if user_signed_in? && !comment.is_sub_comment?
          = form_for [@video, @new_comment], :remote => true, html: { method: :post, :class => "needs-validation", :novalidate => true } do |f|
            = f.hidden_field :user_id, value: current_user.id
            = f.hidden_field :parent_id, value: comment.id
            .input-group
              = f.text_area :body, :class => "form-control", :placeholder => "Leave a reply...", :style => "resize: none;", :required => true
              = f.submit "SUBMIT", class: "input-group-addon btn btn-primary comment-submit comment-reply", data: {disable_with: "..."}
              .invalid-feedback You must enter some text to reply!


:javascript
  $("a.delete-comment").click(function() {
    $(this).parents(".comment").first().slideUp("slow", function(){});
  });

  $(".comment-reply").click(function() {
    $(this).parents(".replies-wrapper").first().find(".replies").addClass("replies-append-here");
  });

  $(".reply-link").click(function(e) {
    e.preventDefault();
    var form = $(this).siblings(".replies-wrapper").find(".reply-form")
    form.slideDown("fast", function() {});
    form.find("#comment_body").focus();
  });

app/views/videos/_comments.html.haml
.row.video-comments-section
  .col-12
    %h4 COMMENTS
  .col-12
    - if user_signed_in?
      = form_for [@video, @new_comment], :remote => true, html: { method: :post, :class => "needs-validation", :novalidate => true} do |f|
        = f.hidden_field :user_id, value: current_user.id
        .input-group
          = f.text_area :body, :class => "form-control", :placeholder => "Leave a comment...", :style => "resize: none;", :required => true, disable_with: "..."
          = f.submit "SUBMIT", class: "input-group-addon btn btn-primary comment-submit", data: {disable_with: "..."}
          .invalid-feedback You must enter some text to leave a comment!
      %br
    - else
      = link_to("Sign up", new_user_registration_path) + " or " + link_to("sign in", new_user_session_path) + " to comment"
  .col-12.comments
    - @video.comments.each do |c|
      = render partial: "comment", object: c, as: :comment
    - unless @video.comments.any?
      %p There doesn't appear to be any comments yet...

app/views/videos/_rating.html.haml
%table
  %tr
    %td.stars
      - if @video.ratings.any?
        - starValue = 1
        - (@video.average_rating.floor).times do |i|
          %i.mi.md-36.star(value=starValue) star
          - starValue = starValue + 1
        - if (@video.average_rating % 1.0) >= 0.5
          %i.mi.md-36.star(value=starValue) star_half
          - starValue = starValue + 1
        - elsif (@video.average_rating % 1.0) > 0.0
          %i.mi.md-36.star(value=starValue) star_border
          - starValue = starValue + 1
        - (5 - @video.average_rating.ceil).times do |i|
          %i.mi.md-36.star(value=starValue) star_border
          - starValue = starValue + 1
      - else
        - 5.times do |i|
          - starValue = i+1
          %i.mi.md-36.star(value=starValue) star_border
    %td.rating-text
      - if @video.ratings.any?
        = "#{@video.average_rating.round(1)}/5 - #{pluralize(@video.ratings.count, 'rating')}"
      - else
        No ratings yet.
  %tr
    %td{:colspan => 2}
      - if user_signed_in?
        = form_for [@video, @rating], :remote => true do |f|
          = f.hidden_field :user_id, value: current_user.id
          = f.hidden_field :value, value: 4
          %button.btn.btn-primary.d-none#new_rating_button= "SUBMIT"
      - else
        = link_to("Sign up", new_user_registration_path) + " or " + link_to("sign in", new_user_session_path) + " to rate videos"

:javascript
  var initialStarHtml = [];
  $(document).ready(function() {
    for (var i = 1; i <= 5; i++) {
      initialStarHtml[i] = $("i.star[value=" + i + "]").html();
    }
    $("i.star").hover(
    function() { // mouseenter
      var hoveredStarValue = $(this).attr("value");
      for (var i = 1; i <= hoveredStarValue; i++) {
        $("i.star[value=" + i + "]").html("star");
      }
      ++hoveredStarValue;
      for (var i = hoveredStarValue; i <= 5; i++) {
        $("i.star[value=" + i + "]").html("star_border");
      }
    },
    function() { // mouseleave
      for (var i = 1; i <= 5; i++) {
        $("i.star[value=" + i + "]").html(initialStarHtml[i]);
      }
    });

    $("i.star").click(function() {
      $("#rating_value").val($(this).attr("value"));
      $("#new_rating_button").click();
    });
  });

app/views/videos/_video_home.html.haml
.video
  = link_to video_url(video) do
    = image_tag (video.image? ? video.image : 'image_placeholder.png'), :class => "img-fluid"
    .video-inner
      .title
        = video.title
      %hr
      / %table.duration
      /   %td.time-icon
      /     %i.mi.md-18 access_time
      /   %td.time-text
      /     = "3:15"
      .rating
        - if video.ratings.any?
          .stars
            - starValue = 1
            - (video.average_rating.floor).times do |i|
              %i.mi.md-18.star(value=starValue) star
              - starValue = starValue + 1
            - if (video.average_rating % 1.0) >= 0.5
              %i.mi.md-18.star(value=starValue) star_half
              - starValue = starValue + 1
            - elsif (video.average_rating % 1.0) > 0.0
              %i.mi.md-18.star(value=starValue) star_border
              - starValue = starValue + 1
            - (5 - video.average_rating.ceil).times do |i|
              %i.mi.md-18.star(value=starValue) star_border
              - starValue = starValue + 1
        - else
          .nostars
            No ratings yet
      .author
        = video.author
      .date
        = video.date_friendly

app/views/videos/index.html.haml
.col-12.d-md-none
  = render partial: "home/filter"
.col-12
  %h4.home-section-title
    - if @video_filter.any_filters?
      %span.blue FILTERED
    - else
      %span.blue SAMPLE
    TALKS
.col-12.home-section-title-under
  .spacer-line
.col-12.col-md-9
  .row
    - @videos.each do |vid|
      .col-12.col-sm-6.col-lg-3{ :style => "margin-bottom: 35px;" }
        = render partial: "videos/video_home", object: vid, as: :video
    - unless @videos.any?
      .col-12
        %p We weren't able to find any videos based on your search criteria.
        %p Try removing some filters to find what you're looking for.
.col-12.col-md-3.d-none.d-md-flex
  = render partial: "home/filter"

app/views/videos/show.html.haml
.col-sm-12.col-md-9#video-show
  .row
    .col-12
      %h4= @video.title.upcase
    .col-12
      = link_to @video.url, target: "_blank", id: "video_click_link" do
        = image_tag (@video.image? ? @video.image : 'image_placeholder.png'), :class => "img-fluid video-preview"
        .play-button-overlay
          = image_tag("play-button.png")
        .video-overlay.author
          %h3= @video.author.upcase
        / .video-overlay.duration
        /   %h3
        /     %i.mi access_time
        /     3:15
    .col-12.col-lg-8.rating
      = render partial: "rating"
    .d-none.d-lg-block.col-lg-4.date.text-right
      .date-margin
        = @video.date_friendly
    .d-lg-none.col-12.date
      = @video.date_friendly
    .col-12.mb-5
      - @video.categories.each do |c|
        = link_to c.name, "/videos?topic=#{c.id}", :class => "badge badge-secondary"
    / .col-12.transcript
    /   %p= @video.transcript
  = render partial: "comments"
.col-sm-12.col-md-3#related-videos
  .row
    - if user_signed_in? && current_user.admin?
      = render partial: "admin"
    .col-12
      %h4= "RELATED VIDEOS"
    - @video.related_videos.each do |vid|
      .col-12
        = render partial: "videos/video_home", object: vid, as: :video
        %br
#video_form_container
  = form_tag("#{@video.id}/user_click", method: :post, :remote => true, :id => "video_click_form")

:javascript
  $("a#video_click_link").click(function() {
    $("#video_click_form").trigger("submit.rails");
  });