config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'

  resources :videos, :only => [:index, :show] do
    member do
      post "user_click"
      post "set_active_status"
      post "set_featured_status"
    end
  	resources :comments, only: [:create, :update]
  	resources :ratings, only: [:create, :update]
  end
  resources :comments, only: [:destroy]

  get "/about", to: "home#about"
  post "/about", to: "home#send_contact"

  get "/admin", to: "admin#index"
  post "/admin/crawl_page", to: "admin#crawl_page"
  post "/admin/update_about", to: "admin#update_about"
  post "/admin/crawl_categories", to: "admin#crawl_categories"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:send_contact]
  before_action :get_about_us_variables, only: [:about, :send_contact]
  def home
  	@featured_talks = Video.where(featured: true).sample(4)
  	
    @recent_talks = Video.where(date: Video.maximum("date")).sample(4)
    # There should be more than 4 videos matching latest date since they come in waves from conference,
    # but just in case.....
    if @recent_talks.count() != 4
      @recent_talks = Video.order(date: :desc).take(20).sample(4)
    end

    # TODO: move to scope somehow?
  	@popular_talks = Video.left_outer_joins(:ratings).where.not(ratings: {id: nil}).distinct
      .select{ |vid| vid.average_rating > 3.0}.sort_by{ |vid| vid.average_rating}.reverse.first(4)

    @video_filter = VideoFilter.new
    @video_filter.clear
    load_filter_inputs_data
  end

  # GET
  def about
  end

  # POST (contact form listener)
  def send_contact
    GeneralMailer.with(
      name: params[:name],
      email: params[:email],
      message: params[:message]).contact_email.deliver_later
    
    flash.now[:notice] = 'Your message has been received.'
    render "about"
  end

  private

  def get_about_us_variables
    @name = nil
    @email = nil
    if user_signed_in?
      @name = current_user.full_name
      @email = current_user.email
    end
    @about_us_text = SiteData.first.about_us
  end
end

app/views/home/_carousel.html.haml
#homeCarousel.carousel.slide{"data-ride" => "carousel"}
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#homeCarousel"}
    %li{"data-slide-to" => "1", "data-target" => "#homeCarousel"}
    %li{"data-slide-to" => "2", "data-target" => "#homeCarousel"}
    %li{"data-slide-to" => "3", "data-target" => "#homeCarousel"}
  .carousel-inner
    .carousel-item.active
      = image_tag "home-carousel-6-web.jpg", :class => "d-block w-100", :alt => "First slide"
      .carousel-caption.d-none.d-md-block
        %h5 Find Your Potential.
        %p Join Best Church Talks to find the ideas and inspiration you need for yourself and those you serve.
    .carousel-item
      = image_tag "home-carousel-5-web.jpg", :class => "d-block w-100", :alt => "Second slide"
      .carousel-caption.d-none.d-md-block
        %h5 Get Inspired.
        %p Join Best Church Talks to find the ideas and inspiration you need for yourself and those you serve.
    .carousel-item
      = image_tag "home-carousel-7-web.jpg", :class => "d-block w-100", :alt => "Third slide"
      .carousel-caption.d-none.d-md-block
        %h5 Join The Community.
        %p Join Best Church Talks to find the ideas and inspiration you need for yourself and those you serve.
    .carousel-item
      = image_tag "home-carousel-3-web.jpg", :class => "d-block w-100", :alt => "Third slide"
      .carousel-caption.d-none.d-md-block
        %h5 Give Back.
        %p Join Best Church Talks to find the ideas and inspiration you need for yourself and those you serve.
    %a.carousel-control-prev{"data-slide" => "prev", :href => "#homeCarousel", :role => "button"}
      %span.carousel-control-prev-icon{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.carousel-control-next{"data-slide" => "next", :href => "#homeCarousel", :role => "button"}
      %span.carousel-control-next-icon{"aria-hidden" => "true"}
      %span.sr-only Next
%br
%br

app/views/home/_filter.html.haml
.home-filter
  .filter-header
    FIND A TALK
  .filter-filters
    = form_tag(videos_path, :method => "GET") do
      = label_tag "rating", "Rating:"
      = select_tag "rating", options_for_select(@ddl_rating_options, @video_filter.rating), include_blank: "---Any---", class: "custom-select"
      = label_tag "title", "Title:"
      = text_field_tag "title", @video_filter.title, class: "form-control"
      = label_tag "author", "Speaker:"
      = text_field_tag "author", @video_filter.author, class: "form-control"
      = label_tag "date", "Date:"
      = select_tag "date", options_for_select(@ddl_date_options, @video_filter.date), include_blank: "---Any---", class: "custom-select"
      = label_tag "topic", "Topic:"
      = select_tag "topic", options_for_select(@categories.collect {|c| [ c['name'], c['id'] ] }, @video_filter.topic), include_blank: "---Any---", class: "custom-select"
      / = label_tag "gender", "Gender:" / target demographic gender filter
      / = select_tag "gender", "<option>Male</option><option>Female</option><option>Other</option>".html_safe, include_blank: "---Any---", class: "custom-select"
      / = label_tag "venue", "Venue:" / conference/category of video. TODO: Need to capture.
      / = select_tag "venue", "<option>Male</option><option>Female</option><option>Other</option>".html_safe, include_blank: "---Any---", class: "custom-select"
      / = label_tag "length", "Length:"
      / = select_tag "length", options_for_select(@ddl_length_options, @video_filter.length), include_blank: "---Any---", class: "custom-select"
      / = label_tag "gender", "Review Age Range:" / this is like 'target demographic' age filter
      / = select_tag "gender", "<option>Male</option><option>Female</option><option>Other</option>".html_safe, include_blank: "---Any---", class: "custom-select"
      = submit_tag "SEARCH", :class => "btn btn-primary"

app/views/home/_footer.html.haml
.container-fluid
  .row.quick-links
    .container
      .row
        .col-12
          %h5 QUICK LINKS
          %hr
        .col-3
          = link_to("General Conference", "https://www.lds.org/general-conference/conferences")
          %br
          = link_to("Church News", "https://www.lds.org/church/news")
          %br
          = link_to("Find a Meetinghouse", "https://www.lds.org/maps/meetinghouses/")
        .col-3
          = link_to("Mormon Newsroom", "https://www.mormonnewsroom.org/")
          %br
          = link_to("Teaching in the Savior's Way", "https://www.lds.org/manual/teaching-in-the-saviors-way")
        .col-3
          = link_to("Ministering", "https://www.lds.org/ministering")
          %br
          = link_to("Upcoming Church Events", "https://www.lds.org/church/events/archive/events")
        .col-3
          = link_to("Come, Follow Me Resources", "https://www.lds.org/manual/come-follow-me")
          %br
          = link_to("FamilySearch.org", "https://www.familysearch.org/en/")
.container
  .row.footer
    .col-12.footer-site-links
      %p.text-center
        - if user_signed_in?
          = link_to "MY ACCOUNT", edit_user_registration_path
          %span.spacer= "|"
          = link_to "SIGN OUT", destroy_user_session_path, { :method => :delete }
          %span.spacer= "|"
        - else
          = link_to "SIGN UP", new_user_registration_path
          %span.spacer= "|"
          = link_to "SIGN IN", new_user_session_path
          %span.spacer= "|"
        = link_to("ABOUT US", "/about")
        %span.spacer= "|"
        = link_to("CONTACT", "/about")
    .col-12.social-media-links.text-center
      = image_tag("social-media-links.png")
    .col-8.offset-2
      %hr
    .col-12.text-center.copyright
      = "Copyright #{Time.current.year} Best Church Talks. All rights reserved."

app/views/home/about.html.haml
.col-sm-7
  %h4 ABOUT BEST CHURCH TALKS
  #about-us
    = simple_format(@about_us_text)

.col-sm-5
  %h4 CONTACT
  = form_tag('about', :method => "POST") do
    .form-group
      = label_tag "name", "Name"
      = text_field_tag "name", @name, :class => "form-control", :required => true
    .form-group
      = label_tag "email", "Email"
      = email_field_tag "email", @email, :class => "form-control", :required => true
    .form-group
      = label_tag "message", "How can we help?"
      = text_area_tag "message", "", :class => "form-control", :required => true, rows: 6
    = submit_tag "SUBMIT", :class => "btn btn-primary"
    %br
    %br

app/views/home/home.html.haml
- content_for :carousel do
  = render partial: "carousel"
.col-12
  %h4.home-section-title
    %span.blue FEATURED
    TALKS
.col-12.home-section-title-under
  .spacer-line
.col-12.col-md-9
  .row.videos-row
    .col-12
    - @featured_talks.each do |vid|
      .col-12.col-sm-6.col-lg-3
        = render partial: "videos/video_home", object: vid, as: :video
  .row.videos-row.d-none.d-md-flex
    .col-12
      %h4.home-section-title
        %span.blue MOST
        RECENT
    .col-12.home-section-title-under
      .spacer-line
    - @recent_talks.each do |vid|
      .col-12.col-md-6.col-lg-3
        = render partial: "videos/video_home", object: vid, as: :video
  .row.videos-row.d-none.d-md-flex
    .col-12
      %h4.home-section-title
        %span.blue MOST
        POPULAR
    .col-12.home-section-title-under
      .spacer-line
    - @popular_talks.each do |vid|
      .col-12.col-md-6.col-lg-3
        = render partial: "videos/video_home", object: vid, as: :video
.col-12.col-md-3
  = render partial: "filter"

:javascript
  // carousel activate
  $('.carousel').carousel();